"""Add comic colors

Revision ID: 588936176906
Revises: 4e35bf26430b
Create Date: 2025-12-04 08:51:36.805131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588936176906'
down_revision: Union[str, None] = '4e35bf26430b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_primary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('color_secondary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('color_secondary')
        batch_op.drop_column('color_primary')

    # ### end Alembic commands ###
