"""Add count column to comic model

Revision ID: 6e87b61c6ec5
Revises: 7be475332664
Create Date: 2025-12-01 14:38:10.887910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e87b61c6ec5'
down_revision: Union[str, None] = '7be475332664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
