"""Add missing indexes to comic table

Revision ID: 8cc213272f14
Revises: dfd8ecbd112e
Create Date: 2025-12-05 16:31:35.598531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc213272f14'
down_revision: Union[str, None] = 'dfd8ecbd112e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comics_publisher'), ['publisher'], unique=False)
        batch_op.create_index(batch_op.f('ix_comics_series_group'), ['series_group'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comics_series_group'))
        batch_op.drop_index(batch_op.f('ix_comics_publisher'))

    # ### end Alembic commands ###
