"""Add age_rating, language_iso fields to comics table

Revision ID: c9baaf8d18e1
Revises: 0dbd17215215
Create Date: 2025-12-02 16:25:54.792437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9baaf8d18e1'
down_revision: Union[str, None] = '0dbd17215215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_rating', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('language_iso', sa.String(), nullable=True))

    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_id'))

    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('language_iso')
        batch_op.drop_column('age_rating')

    # ### end Alembic commands ###
